/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sayit;

public class App {

    public static void main(String[] args) {
        Interface i = new Interface();
        i.init();
    }
}
